### ISSUE TITLE
bloom filter

### ISSUE THREAD

**Issue by shenlinxian** [gitferry/bamboo#3]
你好，我在编译server时提醒undefined BloomFilter，是需要什么额外的支持吗？

**Comment by gitferry** [comment]
由于.gitignore配置不当导致mempool下的bloom.go没有上传到repo。现在已经fix了，感谢指出问题！

**Comment by shenlinxian** [comment]
您好，我目前在做hotstuff的工作，看到您在github上的工作，希望能复现您在论文中的实验结果。实验环境是本地虚拟机，我通过更改bsize、Throttle、Concurrency这三个参数，吞吐量最大也只能到25000左右，但我使用https://github.com/hot-stuff/libhotstuff 时，吞吐量能轻松达到10<https://github.com/hot-stuff/libhotstuff%20时，吞吐量能轻松达到10>万，看您论文里的实验结果应该不会差这么多，是还有其他参数需要调节吗？

**Comment by gitferry** [comment]
感谢您的兴趣，如果方便的话可以加我的wx讨论：gaimiaomiao621
