### ISSUE TITLE
Fast-HotStuff benchmark results

### ISSUE THREAD

**Issue by swdee** [gitferry/bamboo#5]
We see in the code base you have added Fast-HotStuff as a consensus option, are you planning to do an update of the technical report https://arxiv.org/pdf/2103.00777.pdf to include it?

What differences did you see with Fast-HotStuff in your benchmarking compared to HotStuff?

**Comment by gitferry** [comment]
@swdee Thanks for your notice but we're not considering including the eval of Fast-HotStuff in the report right now. I think its performance should be close to two-chain hotstuff since it also has a two-chain commit rule.
